spring.application.name=helpdesk-ti
spring.profiles.default=dev
server.port=${PORT:8080}
server.servlet.session.timeout=8h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=${SESSION_SAME_SITE:lax}
server.servlet.session.cookie.secure=${SESSION_SECURE:false}
server.error.include-message=never
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.jackson.time-zone=UTC
app.public-url=${PUBLIC_FRONTEND_URL:}
app.allowed-origins=${FRONTEND_ORIGINS:}
app.bootstrap-email=${BOOTSTRAP_EMAIL:}
app.bootstrap-password=${BOOTSTRAP_PASSWORD:}
app.sla-response-minutes=${SLA_RESPONSE_MINUTES:5}
app.sla-resolution-minutes=${SLA_RESOLUTION_MINUTES:10}

app.microsoft.enabled=${MICROSOFT_ENABLED:false}
app.microsoft.tenant-id=${MICROSOFT_TENANT_ID:}
app.microsoft.client-id=${MICROSOFT_CLIENT_ID:}
app.microsoft.client-secret=${MICROSOFT_CLIENT_SECRET:}
app.microsoft.redirect-uri=${MICROSOFT_REDIRECT_URI:https://projetopcuc.onrender.com/login/oauth2/code/microsoft}
app.bootstrap-microsoft-object-id=${BOOTSTRAP_MICROSOFT_OBJECT_ID:}
